knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: id
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'