version: '3.3'

services:
  nginx:
    image: nginx:1.20
    ports:
      - 80:80
    volumes:
      - ./:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: ./.docker/php
    working_dir: /var/www/php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/php
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=IDE"
    depends_on:
      - mariadb
          
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb-data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    links:
      - mariadb:db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    volumes:
      - pma-data:/var/lib/pma


volumes:
  mariadb-data:
  pma-data:
