version: '3.3'

services:
  nginx:
    image: nginx:1.20
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: ./.docker/php
    restart: always
    working_dir: /var/www/php
    volumes:
      - .:/var/www/php
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=IDE"
    depends_on:
      - mariadb
      - rabbitmq
      - mailcatcher
          
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb-data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    links:
      - mariadb:db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - pma-data:/var/lib/pma

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "8000:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mailcatcher:
    image: dockage/mailcatcher
    ports:
      - "1080:1080"
    volumes:
      - mailcatcher_data:/var/lib/mailcatcher

volumes:
  mariadb-data:
  pma-data:
  rabbitmq_data:
  mailcatcher_data:
